Fix missing bookmarked references IDs
There are cases where a page's children have startPositionIds lower
than previous page's endPositionId. In such cases, this situation led
to certain IDs never being bookmarked in the PDF.

Any attempted links to one of the missing IDs leads to crashing with:
	ValueError: format not resolved, probably missing URL scheme or undefined destination target for 'XXXXX'